name: Build pyston_lite wheels

#on: [workflow_dispatch]
on: [workflow_dispatch, push]

jobs:
  build_pyston_lite_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]

    steps:
      - uses: actions/checkout@v2
      - name: checkout submodules
        run: |
          git submodule update --init pyston/LuaJIT pyston/bolt

      - name: install macOS depedencies
        if: ${{ startsWith(matrix.os, 'macos') }}
        run: |
          curl https://www.python.org/ftp/python/3.8.10/python-3.8.10-macosx10.9.pkg -o python.pkg
          sudo installer -pkg python.pkg -target /

          brew install luajit-openresty gcc@11
          ln -s /usr/local/opt/luajit-openresty/bin/luajit /usr/local/bin/
          echo "CC=gcc-11" >> $GITHUB_ENV

      - name: create pyston_lite_autoload wheel
        if: ${{ startsWith(matrix.os, 'macos') }}
        working-directory: pyston/pyston_lite
        run: |
          make package_autoload
          mkdir wheelhouse/
          cp autoload/dist/pyston_lite_autoload* wheelhouse/

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.6.0
        with:
          package-dir: pyston/pyston_lite
        env:
          CIBW_BUILD: cp38-*
          CIBW_SKIP: "*_i686 *musllinux*"
          CIBW_BUILD_VERBOSITY_MACOS: 2
          #CIBW_BEFORE_ALL_LINUX: yum install -y luajit; make bolt -j`nproc`
          CIBW_BEFORE_ALL_LINUX: yum install -y luajit; export NOBOLT=1; export NOPGO=1
          CIBW_TEST_COMMAND: pip install {package}/wheelhouse/pyston_lite_autoload*.whl && python -m test -j0 -x test_code test_distutils test_ensurepip test_minidom test_site test_xml_etree test_xml_etree_c test_capi
          NOPGO: 1
          NOBOLT: 1

      - name: install macOS depedencies
        if: ${{ startsWith(matrix.os, 'macos') }}
        run: |
          brew install luajit-openresty gcc@11
          ln -s /usr/local/opt/luajit-openresty/bin/luajit /usr/local/bin/
          echo "CC=gcc-11" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
