name: GitHub Actions CI
on: [push, pull_request]
jobs:
  pyston_lite_macos:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: checkout submodules
        run: |
          git submodule update --init pyston/LuaJIT
      - name: run code
        run: |
          brew install luajit-openresty
          cd pyston/pyston_lite; make test

