name: GitHub Actions CI
on: [push, pull_request]
jobs:
  pyston_lite_macos:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: run code
        run: |
          # install official python3.8 package
          curl https://www.python.org/ftp/python/3.8.10/python-3.8.10-macosx10.9.pkg -o python.pkg
          sudo installer -pkg python.pkg -target /

          cd pyston/pyston_lite

          python3.8 -m venv env
          ./env/bin/pip install wheel
          ./env/bin/pip install wheelhouse/pyston_lite*
          SHOW_JIT_STATS=1 lldb -o run ./env/bin/python ../test/inplace_math.py
