name: GitHub Actions CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - build: unopt
            PYSTON_UNOPT_BUILD: 1
          - build: opt
            PYSTON_UNOPT_BUILD: 0
    steps:
      - uses: actions/checkout@v2
      - name: checkout submodules
        run: |
          git submodule update --init pyston/LuaJIT pyston/macrobenchmarks
      - name: build and test pyston
        env:
          PYSTON_UNOPT_BUILD: ${{ matrix.PYSTON_UNOPT_BUILD }}
        run: |
          pyston/conda/build_pkgs.sh
      - name: Archive packages
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: |
            release/conda_pkgs/
